### ISSUE TITLE
Prompt shows but name and icon are not visible on macOS

### ISSUE THREAD

**Issue by davidhemphill** [jorangreef/sudo#127]
`sudo-prompt` is not correctly showing the name or icon file for the app when passed an object with `name` or `icns` keys. I was able to replicate the issue on a fresh Electron project with just this package installed. The following code:

```js
import sudo from 'sudo-prompt'

let options = {
  name: 'Valet Lite',
  icns: '/Applications/Valet Lite.app/Contents/Resources/Valet Lite.icns',
}

sudo.exec('ls', options, (error, stdout, stderr) => {
  if (error) throw error
  console.log(stdout)
  console.log(stderr)
})
```

Produces this:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/58970/85652319-04b84900-b670-11ea-81f7-57f957da5a1f.png">

**Comment by davidhemphill** [comment]
I downloaded the repository and ran `node test.js` and the errant behavior was present as well. This is on Catalina 10.15.5.

**Comment by jorangreef** [comment]
Thanks @davidhemphill I can confirm this. Do you know of any changes in Info.plist behavior across macOS that would affect this? That's what we're using to set the app name and icon.

**Comment by davidhemphill** [comment]
Sadly, I don't as that's out of my area of expertise. I'll do some research on my end and see if I can come up with anything.

**Comment by idanwork** [comment]
Hi I have the same issue after updated to Catalina 10.15.5, 

The same product works as expected on older versions of macOS and older versions of Catalina (10.15.4 and older).

I didn't have the chance to check what is causing, I'll try to make some time for checking this.

**Comment by idanwork** [comment]
Hi Guys,

I'm sorry to say that I wasn't able to figure it out yet.
I tried to recreate the applet using Catalina Xcode 11.

It didn't change anything, Icon and name are missing.

I'll try next following the suggested path under this issue
https://github.com/jorangreef/sudo-prompt/issues/109

Seems Catalina will require new approach for running elevated commands.

**Comment by idanwork** [comment]
Sorry for spamming,
Just got word that on 10.15.6 it was fixed ;)
So it was indeed an apple issue

**Comment by kotapeter** [comment]
@idanwork Thank you! I can also confirm it, I've just updated MacOS to `10.15.6` and `sudo-prompt` works as expected :) This issue can be closed.

**Comment by jorangreef** [comment]
Thanks everyone!
